# This is a basic workflow for github actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_awesome_lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: fetch
        run: git fetch origin main:main --depth=1

      - name: find repo
        run: git diff main readme.md | grep ^+ | grep -Eo 'https.*#readme' | sed 's/#readme//' | xargs -I {} echo "::set-env name=REPO_TO_LINT::{}"

      # - name: validate repo
      #   run: if [ -z ${REPO_TO_LINT+x} ]; then echo "var is unset"; else echo "var is set to '$var'"; fi

      - name: clone
        run: echo "cloning $REPO_TO_LINT" && mkdir cloned && cd cloned && git clone "$REPO_TO_LINT" .
      
      - name: lint
        run: npx awesome-lint      